### ISSUE TITLE
Please avoid using this tool for now, sends invalid requests

### ISSUE THREAD

**Issue by Dr-Desty-Nova** [code4clouds/ampsaaswebhook#4]
If you stumbled here by accident following link from [here](https://www.microsoftpartnercommunity.com/t5/Microsoft-AppSource-and-Azure/New-tool-for-testing-SaaS-webhook/td-p/16302), for now please avoid using it to test your systems.

Here's an example of what it sends to the webhook:

```
POST /webhook HTTP/1.1
Content-Type: application/json
host: localhost:8080
accept: application/json
content-length: 435
Connection: close

{
    "id":"733278fb-a728-4fe8-8198-75c0310b9209",
    "activityId":"82eda8ea-262c-41ff-a186-7d92a4d8c8d8",
    "subscriptionId":"63435a68-1dc0-41f2-806d-34b321e05cab",
    "publisherId":"9a728bcd-23f4-4396-9031-d97a626e1b82",
    "offerId":"1383d7b6-959c-4a0d-8386-da83bf6af92c",
    "planId":"0db21ed8-2edb-4e8e-93bd-5d1c443085b6",
    "quantity":"60",
    "timeStamp":"function now() { [native code] }",
    "action":"82eda8ea-262c-41ff-a186-7d92a4d8c8d8",
    "status":"Succeeded"
}
```
* `id` field can be arbitrary string, at least for now, see [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/47736)
* `TimeStamp` field is some JS nonsense
* `action` is never an UUID, see [docs](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2#implementing-a-webhook-on-the-saas-service)

I hope maintainer of this tool will have time to look at this issue.

**Comment by code4clouds** [comment]
@Dr-Desty-Nova Thanks for the feedback!

All your notes are now fixed.   From your 3 items mentioned above, the id field is correct (per your issue reference).  The team said it is a GUID and not an arbitrary string.

**Comment by Dr-Desty-Nova** [comment]
@code4clouds great! And thanks for fast response, appreciate it.
